sudo: required
services:
  - docker

install:
  - pip install PyYAML
  - pip install virtualenv
  - |
    test -e Gemfile || cat <<EOF > Gemfile
    source 'https://rubygems.org'
    gem 'rake'
    gem 'test-kitchen'
    gem 'kitchen-docker'
    gem 'kitchen-inspec'
    gem 'inspec'
    gem 'kitchen-salt', :git => 'https://github.com/salt-formulas/kitchen-salt.git'
  - bundle install

env:
    - PLATFORM=trevorj/salty-whales:trusty SUITE=horizon_no_ssl
    - PLATFORM=trevorj/salty-whales:xenial SUITE=horizon_no_ssl
    - PLATFORM=trevorj/salty-whales:trusty SUITE=horizon_with_ssl
    - PLATFORM=trevorj/salty-whales:xenial SUITE=horizon_with_ssl
    - PLATFORM=trevorj/salty-whales:trusty SUITE=proxy
    - PLATFORM=trevorj/salty-whales:xenial SUITE=proxy
    - PLATFORM=trevorj/salty-whales:trusty SUITE=redirect
    - PLATFORM=trevorj/salty-whales:xenial SUITE=redirect
    - PLATFORM=trevorj/salty-whales:trusty SUITE=static
    - PLATFORM=trevorj/salty-whales:xenial SUITE=static
    - PLATFORM=trevorj/salty-whales:trusty SUITE=stats
    - PLATFORM=trevorj/salty-whales:xenial SUITE=stats

before_script:
  - set -o pipefail
  - make test | tail

script:
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml bundle exec kitchen test -t tests/integration

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6123573504759330786b
    on_success: change  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    on_cancel: never    # options: [always|never|change] default: always
    on_error: never    # options: [always|never|change] default: always
  email: false
